repos:
- repo: https://github.com/ambv/black
  rev: 21.9b0
  hooks:
  - id: black
    args:
      - --line-length=88
    language_version: python3.9
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2  # pick a git hash / tag to point to
  hooks:
  - id: flake8
    args: # arguments to configure flake8
      # making isort line length compatible with black
      - "--max-line-length=95"